### PR TITLE
Get assaytype endpoint

### PR DESCRIPTION
**Pull request by ChuckKollar**
Create new endpoints that exactly duplicate the functionality (exact inputs/outputs) of HuBMAP Search API [GET /assaytype/<name>] endpoint by pulling all information from the SenNet/HuMAP application specific ontologies (instead of the assay_types.yaml file).

### CODE REVIEW

**Review by AlanSimmons — COMMENTED** [review]
Although the request was to replace the original call, we're also expanding the available information for assay types. For example, we were asked to identify data_types by whether they were lab-processed (dataset_provider = "External Provider"). In other words, we are replacing a call to read assay_types.yaml with a call that returns _more_ information for assay types from the ontology. In other words, your endpoint should return everything that the query returns.

I also wonder whether the references to _record[x]_ in lines 910-914 should not actually include the key names--e.g., record['dataset_provider'].

**Comment by ChuckKollar** [comment]
> Although the request was to replace the original call, we're also expanding the available information for assay types. For example, we were asked to identify data_types by whether they were lab-processed (dataset_provider = "External Provider"). In other words, we are replacing a call to read assay_types.yaml with a call that returns _more_ information for assay types from the ontology. In other words, your endpoint should return everything that the query returns.
> 
> I also wonder whether the references to _record[x]_ in lines 910-914 should not actually include the key names--e.g., record['dataset_provider'].

My understanding of this work come from our (Bill, you, and I) discussions on Slack. When Bill said to make a replace endpoint for the one in search-api, I tried to do just that. It returns the information that is returned by search-api and no more. I know that you have more information, and we could (likely) return it without breaking anything because someone not looking for it would not find it and that would be fine. It's a requirements issue, we need to ask Bill.

About the use of the indexes rather than the names in the record, I found that the .get('name') didn't actually work. I did find that treating the record as an array worked. I did not explore using names as you have suggested. The only difference between ['foo'] and .get('foo
) that I am aware of is that in the first case you will get a KeyException(?) error if the key does not exist and in the latter case you will get null and no error throw. I don't like using the subscripts, but it worked, and the .get did not. So, I honestly don't know what's going on there. I can take another look at it.

**Comment by AlanSimmons** [comment]
The code that I used in the dataset_get routine has the line:

```
dataset: [DatasetPropertyInfo] = DatasetPropertyInfo(record.get('alt_names'),
...
```

which worked for me.

**Comment by AlanSimmons** [comment]
@shirey We're not just replacing the read of assay_types.yaml, but including new information, such as the dataset provider (IEC vs. external). Correct?

**Comment by ChuckKollar** [comment]
I changed the Neo4j record access from numeric indexes to named ones.

**Comment by shirey** [comment]
> @shirey We're not just replacing the read of assay_types.yaml, but including new information, such as the dataset provider (IEC vs. external). Correct?

@AlanSimmons Correct, but I told @ChuckKollar to get this released as he has it and create a new card/issue to include the new information in a future (hopefully next) sprint.

**Comment by shirey** [comment]
From: @ChuckKollar 
> I changed the Neo4j record access from numeric indexes to named ones.
@AlanSimmons  fyi ^^^^^^  @ChuckKollar this won't affect neo4j performance, will it?  Also, what if someone else is expecting there to be numeric indices-- folks outside of HuBMAP/Pitt use this service and these databases.

**Comment by AlanSimmons** [comment]
The query itself requires only a few milliseconds, so I doubt that changing references to named references from numerical indexes will affect performance.

I have no idea whether anyone would expect numeric indexes. The named attributes match the names of attributes in the YAML file.

**Review by AlanSimmons — APPROVED** [review]

**Comment by yuanzhou** [comment]
I changed the base branch to `dev-integrate` so we can test on DEV first.

**Review by yuanzhou — APPROVED** [review]

**Pull request merged**
